class_name GlobalTypes

enum Vessels { VEIN, CAPILLARIES, ARTERY, AORTA, VENA_CAVA, LEFT_ATRIUM, LEFT_VENTRICLE, RIGHT_ATRIUM, RIGHT_VENTRICLE, PULMONARY_ARTERY, PULMONARY_VEIN }

enum Gases { OXYGEN, CARBON_DIOXIDE}

enum Organs { LUNGS, BRAIN, HEART, LIVER, KIDNEYS, PANCREAS }
