class_name GlobalTypes

enum Vessels { VEIN, CAPILLARIES, ARTERY, AORTA, VENA_CAVA, PULMONARY_ARTERY, PULMONARY_VEIN }

enum Gases { OXYGEN, CARBON_DIOXIDE}

enum Organs { LUNGS, BRAIN, HEART, LIVER, KIDNEYS, PANCREAS }

enum Hormones { EPINEPHERINE, DOPAMINE, ACETYLCHOLINE }


